name: landing_page
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.4
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
